Feature/quotas
gestionEnqueteur/appGestionEnqueteur pull request #15
Opened 2023-06-03 07:34 UTC by jeanCodeUnMax

2023-06-03 20:10 UTC, ponche requested changes
Icon et le text n'est pas proportionné. Icon est trop grand par rapport au Texte. 

Maintenant, l’enquêteur  devra prendre des loupe pour lire le texte. 😠 

l'idée de mettre un Icon, c'est de ne pas mettre le texte:  *objectif*

2023-06-03 20:10 UTC, ponche commented on components/DetailCourse.tsx
> +import styles from "./modals/modalStyle";
Pourquoi tu importe Quotas et modalStyle dans le ChronoTopDepart ?

2023-06-03 20:10 UTC, ponche commented on components/DetailCourse.tsx
> -        <Text variant="headlineSmall">842526</Text>
Pourquoi tu supprime mon style ? 😡

2023-06-03 20:10 UTC, ponche commented on components/Quotas.tsx
> +        {"  "}
Icon et value ne sont pas proportionné. 
Icon est trop grand par rapport au texte.

2023-06-05 21:17 UTC, jeanCodeUnMax commented
mise a jour terminé

2023-06-05 21:17 UTC, closed without merging