Feature/use api
gestionEnqueteur/appGestionEnqueteur pull request #47
Opened 2024-06-07 18:26 UTC by Anothays

Création du hook useApi et son test.

2024-06-08 21:44 UTC, jeanCodeUnMax approved these changes

2024-06-08 21:44 UTC, jeanCodeUnMax commented on package.json
> +    "@react-native-async-storage/async-storage": "^1.22.3",
downgrade pourquoi ?

2024-06-08 21:44 UTC, jeanCodeUnMax commented on package.json
> +    "@react-native-masked-view/masked-view": "^0.3.0",
downgrade pourquoi ?

2024-06-08 21:44 UTC, jeanCodeUnMax commented on package.json
> +    "@react-navigation/native": "^6.0.8",
downgrade pourquoi ?

2024-06-08 21:44 UTC, jeanCodeUnMax commented on package.json
> +    "jest": "^29.2.1",
downgrade pourquoi ?

2024-06-08 21:44 UTC, jeanCodeUnMax commented on package.json
> +    "react-native": "^0.74.0",
downgrade pourquoi ?

2024-06-08 21:44 UTC, jeanCodeUnMax commented on package.json
> +    "react-native-gesture-handler": "^2.14.0",
downgrade pourquoi ?

2024-06-08 21:44 UTC, jeanCodeUnMax commented on package.json
> +    "react-native-safe-area-context": "^4.8.2",
downgrade pourquoi ?

2024-06-08 21:44 UTC, jeanCodeUnMax commented on package.json
> +    "react-native-screens": "^3.31.0",
downgrade pourquoi ?

2024-06-08 21:44 UTC, jeanCodeUnMax commented on package.json
> +    "react-native-reanimated": "^3.6.0",
downgrade pourquoi ?

2024-06-09 09:19 UTC, ponche requested changes
**spraise**: super travail. code livré avec les test, juste des petit correctif a faire avant que j'approuve la PR. 

**issue**: ambiguïté sur des noms de commits. et tu as fais des doublon. plusieurs commits on le même noms. 

**question**: vu tu m'avais dit que tu ne pouvais pas installer _React Native Testing Library_ sans avoir la library _react_test_render_. somme nous obligé de dowgradé ? 

**note**: j'ai vu des dowgrade sur des versions mineurs. 

**note**: tu peut éditer les nom des commits avec cette commande `git rebase -i develop`
en ensuite dans l'éditeur tu marque en _reword_.

2024-06-09 09:19 UTC, ponche commented on tests/hook/useApi.test.tsx
> +          urlApi: "http://HelloWorld.com",
**note**: SonarCloud avait bloqué la PR, car il ne considérait que c'était une fail de sécurité. alors que c'est simplement des fake adresse. 

**suggestion**: au prochaine fois, fessons des fake adresse en HTTPS, pour éviter de le faire paniquer. ou bien faire la configuration SonarCloud, afin que SonarCloud ne déclenche plus de fausse alertes.

2024-06-09 09:19 UTC, ponche commented on store/storeAtom.ts
> +export const jwtState = atom<String | undefined>({
**chore**: modifié le type _String_ par le type primitif _string_ 

**note**: signalé par SonarCloud

2024-06-10 15:01 UTC, ponche approved these changes

2024-06-10 15:05 UTC, Anothays commented on package.json
> +    "react-native-screens": "^3.31.0",
Vu avec Rémi 👍 
c'est l'installation des packages de test (sûrement test-react-renderer) qui a fait le downgrade. La CLI expo-doctor dit que tout est ok.

2024-06-10 15:09 UTC, merged